### ISSUE TITLE
Failed to register package 'actions.actions'

### ISSUE THREAD

**Issue by karanshah150696** [GaoQ1/rasa_chatbot_cn#28]
Error:

> action_server_1  | 2019-04-19 09:31:35 INFO     __main__  - Starting action endpoint server...
action_server_1  | 2019-04-19 09:31:35 ERROR    rasa_core_sdk.executor  - Failed to register package 'actions.actions'.
action_server_1  | Traceback (most recent call last):
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 150, in register_package
action_server_1  |     self._import_submodules(package)
action_server_1  |   File "/app/rasa_core_sdk/executor.py", line 137, in _import_submodules
action_server_1  |     package = importlib.import_module(package)
action_server_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
action_server_1  |     return _bootstrap._gcd_import(name[level:], package, level)
action_server_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
action_server_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
action_server_1  |   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
action_server_1  | ModuleNotFoundError: No module named 'actions.actions'
action_server_1  | 2019-04-19 09:31:35 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)
duckling_1       | no port specified, defaulting to port 8000
duckling_1       | Listening on http://0.0.0.0:8000
rasa_nlu_1       | Traceback (most recent call last):
rasa_nlu_1       |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
rasa_nlu_1       |     "__main__", mod_spec)
rasa_nlu_1       |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
rasa_nlu_1       |     exec(code, run_globals)
rasa_nlu_1       |   File "/app/rasa/core/run.py", line 204, in <module>
rasa_nlu_1       |     "Calling `rasa.core.run` directly is "
rasa_nlu_1       | RuntimeError: Calling `rasa.core.run` directly is no longer supported. Please use `rasa shell` instead.
chatwithme_rasa_nlu_1 exited with code 1

Docker-Compose file:

```
version: '3.0'

services:
  rasa_core:
    image: rasa/rasa_core:latest
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/models/current/dialogue:/app/model"
    - "./rasa-app-data/config:/app/config"
    - "./rasa-app-data/project:/app/project"
    command:
    - start
    - -d
    - ./model
    - -c
    - rest
    - -u
    - current/nlu
    - --endpoints
    - config/endpoints.yml

  action_server:
    image: rasa/rasa_core_sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"

  rasa_nlu:
    image: rasa/rasa_nlu:latest-full
    networks: ['rasa-network']
    ports:
    - "5000:5000"
    volumes:
    - "./rasa-app-data/models/:/app/projects"
    - "./rasa-app-data/logs:/app/logs"

  duckling:
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

networks: {rasa-network: {}}
```
