### ISSUE TITLE
rasa.nlu.extractors.crf_entity_extractor WARNING 

### ISSUE THREAD

**Issue by nghuyong** [GaoQ1/rasa_chatbot_cn#49]
非常感谢您的贡献！
我尝试将您的系统迁移到我自己的项目中，具体步骤如下:
在`nlu.md`中添加了训练数据，其中有一条如下:
`- 麻烦帮我发布条[通告](chat)说[国庆节](date)[下午2点](time)[张三的家长](name)来学校[教室](address)参加[毕业典礼](acticities)`
但是当我执行
`rasa train nlu -u data/nlu -c config.yml --out models/nlu`
出现了下面的警告信息:
![image](https://user-images.githubusercontent.com/16462374/60796574-3b1b6080-a1a0-11e9-8f63-8e87fa132b83.png)

我的配置文件如下:
```
language: "zh"

pipeline:
- name: "JiebaTokenizer"
- name: "CRFEntityExtractor"

- name: "rasa_nlu_gao.extractors.jieba_pseg_extractor.JiebaPsegExtractor"
  part_of_speech: ["nr"]

- name: "rasa_nlu_gao.featurizers.bert_vectors_featurizer.BertVectorsFeaturizer"
  ip: '127.0.0.1'
  port: 8001
  port_out: 8002
  show_server_config: True
  timeout: 10000
  check_version: False
- name: "rasa_nlu_gao.classifiers.embedding_bert_intent_classifier.EmbeddingBertIntentClassifier"
```

看到您主页上写到 find-a-part-time job，欢迎联系我👏，可远程，待遇丰厚！ 
我的邮箱是 nghuyong@163.com
期待您的解答与合作！！
